### ISSUE TITLE
Null pointer exception in current develop when right-clicking image

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/autopsy#1288]
Let me know if develop is currently being worked on so much that you don't want bug reports on it, but here's a null pointer exception I got. I added an image, and then photorec ingest failed because I'm not on Windows. Then wanted to right click on the image to rerun ingest modules, and I got this when I right-clicked:
```
java.lang.NullPointerException
	at java.util.Collections.sort(Collections.java:175)
	at org.sleuthkit.autopsy.directorytree.ExtractUnallocAction$UnallocStruct.<init>(ExtractUnallocAction.java:498)
	at org.sleuthkit.autopsy.directorytree.ExtractUnallocAction.<init>(ExtractUnallocAction.java:86)
	at org.sleuthkit.autopsy.directorytree.ExplorerNodeActionVisitor.visit(ExplorerNodeActionVisitor.java:89)
	at org.sleuthkit.autopsy.directorytree.ExplorerNodeActionVisitor.visit(ExplorerNodeActionVisitor.java:52)
	at org.sleuthkit.datamodel.Image.accept(Image.java:221)
	at org.sleuthkit.autopsy.directorytree.ExplorerNodeActionVisitor.getActions(ExplorerNodeActionVisitor.java:59)
	at org.sleuthkit.autopsy.directorytree.DirectoryTreeFilterNode.getDetailActions(DirectoryTreeFilterNode.java:161)
	at org.sleuthkit.autopsy.directorytree.DirectoryTreeFilterNode.getActions(DirectoryTreeFilterNode.java:102)
	at org.openide.nodes.NodeOp.findActions(NodeOp.java:162)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1056)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1555)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mousePressed(MouseUtils.java:180)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6522)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This is a fresh ubuntu 14.04 system running autopsy built from git (current develop branch, checked out today), built with the current sleuthkit (also develop, also checked out today) built following the method in this post:

http://forum.sleuthkit.org/viewtopic.php?f=5&t=106

**Comment by kefir-** [comment]
In case it matters, the image is called "root.disk", and is a backup of an old WUBI root disk image that I had. Here's the image stats according to "file":
```
$ file root.disk 
root.disk: Linux rev 1.0 ext4 filesystem data, UUID=c10e6560-db89-4e50-957d-76c59463ad8d (needs journal recovery) (extents) (large files) (huge files)
```

**Comment by kefir-** [comment]
I opened an old case I created with 3.1.1, and right-clicking works fine. I also tried to run the photorec carver, which failed immediately. Then I tried right-clicking again, and it still works fine.

**Comment by bcarrier** [comment]
Thanks. My guess is that this is the same problem as was fixed in #1287, but that went to the collaborative branch.  It will be applied to develop too.

**Comment by rcordovano** [comment]
This fix has now been pulled into the develop branch as pull request #1293.

**Comment by kefir-** [comment]
Thanks, I'll close this and let you know if I see it again.
