### ISSUE TITLE
java.lang.Exception when closing autopsy

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/autopsy#1289]
I had autopsy open with the case mentioned in issue #1288, and when I closed autopsy, I got the following exception on stdout/stderr (I've included a few extra lines of output above and below the exception):
```
     [exec] Process Virtual Memory: 6,085,050,368
     [exec] May 31, 2015 11:15:17 AM org.sleuthkit.autopsy.ingest.IngestManager cancelAllIngestJobs
     [exec] INFO: Cancelling all ingest jobs called with 0 jobs in jobsById map
     [exec] java.lang.Exception: Cancelling all ingest jobs
     [exec] 	at org.sleuthkit.autopsy.ingest.IngestManager.cancelAllIngestJobs(IngestManager.java:501)
     [exec] 	at org.sleuthkit.autopsy.ingest.IngestManager.handleCaseClosed(IngestManager.java:293)
     [exec] 	at org.sleuthkit.autopsy.ingest.IngestManager$1.propertyChange(IngestManager.java:279)
     [exec] 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
     [exec] 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
     [exec] 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.changeCase(Case.java:209)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.closeCase(Case.java:500)
     [exec] 	at org.sleuthkit.autopsy.corecomponents.Installer.close(Installer.java:104)
     [exec] 	at org.sleuthkit.autopsy.core.Installer.close(Installer.java:198)
     [exec] 	at org.netbeans.core.startup.NbInstaller.closeAsync(NbInstaller.java:738)
     [exec] 	at org.netbeans.ModuleManager.shutDownAsync(ModuleManager.java:1979)
     [exec] 	at org.netbeans.core.startup.ModuleSystem.shutDownAsync(ModuleSystem.java:349)
     [exec] 	at org.netbeans.core.NbLifeExit.doExit(NbLifeExit.java:134)
     [exec] 	at org.netbeans.core.NbLifeExit.run(NbLifeExit.java:94)
     [exec] 	at org.openide.util.Mutex.doEvent(Mutex.java:1343)
     [exec] 	at org.openide.util.Mutex.readAccess(Mutex.java:350)
     [exec] 	at org.netbeans.core.NbLifecycleManager.exit(NbLifecycleManager.java:210)
     [exec] 	at org.netbeans.core.NbLifecycleManager.exit(NbLifecycleManager.java:119)
     [exec] 	at org.netbeans.core.windows.view.ui.MainWindow$6.windowClosing(MainWindow.java:479)
     [exec] 	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
     [exec] 	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
     [exec] 	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
     [exec] 	at java.awt.Window.processWindowEvent(Window.java:2058)
     [exec] 	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
     [exec] 	at java.awt.Window.processEvent(Window.java:2017)
     [exec] 	at java.awt.Component.dispatchEventImpl(Component.java:4881)
     [exec] 	at java.awt.Container.dispatchEventImpl(Container.java:2292)
     [exec] 	at java.awt.Window.dispatchEventImpl(Window.java:2750)
     [exec] 	at java.awt.Component.dispatchEvent(Component.java:4703)
     [exec] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
     [exec] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
     [exec] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
     [exec] 	at java.awt.EventQueue$4.run(EventQueue.java:731)
     [exec] 	at java.awt.EventQueue$4.run(EventQueue.java:729)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
     [exec] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
     [exec] 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
     [exec] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     [exec] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
     [exec] 
     [exec] WARNING [org.sleuthkit.autopsy.keywordsearch.KeywordSearch$CaseChangeListener]: Could not close core.
     [exec] 380029177 closed
     [exec] May 31, 2015 11:15:19 AM org.sleuthkit.autopsy.core.Installer close
     [exec] INFO: org.sleuthkit.autopsy.datamodel.Installer close()
     [exec] May 31, 2015 11:15:19 AM org.sleuthkit.autopsy.core.Installer close
     [exec] INFO: org.sleuthkit.autopsy.ingest.Installer close()
```

**Comment by bcarrier** [comment]
This was already fixed in the collab branch.  It's not really an exception being thrown as much as it was added a while back to help debug some issues and should be removed.  Thanks!

**Comment by rcordovano** [comment]
The debug messages have been removed in the develop branch as well now.

**Comment by kefir-** [comment]
Thanks.
