### ISSUE TITLE
Add data source issue

### ISSUE THREAD

**Issue by lifayk** [sleuthkit/autopsy#1436]
Fresh installation of Autopsy 3.1.3
I created a new case and clicked on Add data source and get this:

Traceback (most recent call last):
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\site.py", line 585, in <module>
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\site.py", line 567, in main
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\site.py", line 300, in addusersitepackages
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\site.py", line 289, in getusersitepackages
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\sysconfig.py", line 416, in get_path
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\sysconfig.py", line 407, in get_paths
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\sysconfig.py", line 180, in _expand_vars
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\sysconfig.py", line 154, in _subst_vars
  File "C:\Soft\Autopsy-3.1.3\autopsy\modules\ext\jython-standalone-2.7.0.jar\Lib\sysconfig.py", line 154, in _subst_vars
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-21: ordinal not in range(128)

**Comment by bcarrier** [comment]
Did you write a python module or install one?   Those modules get loaded and parsed when the Add Data Source button is pressed.

**Comment by lifayk** [comment]
No. I just downloaded distr from official site (sourceforge) for x64 and installed it on Windows 2012 R2. No additional configuration.

**Comment by bcarrier** [comment]
Do you have Python installed anywhere else on your system?  We can't recreate this here, but some googling seems to be that this can be from the library we are using for Python support is looking on the system for other Python code and is hitting a path name that has non-ASCII characters in it.  Any ideas on what that path could be?

**Comment by kefir-** [comment]
Is the C:\Soft\ just a custom install location instead of for instance C:\Program Files?

Could there be any other path components that have non-ascii characters? What is your user name, for instance?

**Comment by lifayk** [comment]
No, I don't have any other Python installations. 
The problem was that my profile name had non-English characters. I've renamed my account name in c:\Users\<ProfileName>. Now it's ok. The issue is solved.

**Comment by kefir-** [comment]
That should be resolved in the code, rather than requiring ascii-only user names.

**Comment by lifayk** [comment]
Agree.

**Comment by bcarrier** [comment]
Thanks for helping to diagnose.  We'll try to recreate this and see if we can change the Jython code to not consider this a fatal error.
