### ISSUE TITLE
Already had dead JAR

### ISSUE THREAD

**Issue by vitalybalashov** [sleuthkit/autopsy#2819]
Hello,
I trying to start autopsy 4.4.0 on my Ubuntu. I've done all steps from documentation and I've seen the liitle window with dog and application starting progress bar, but I've got this stacktrace insted application UI.

```
[exec] WARNING [org.netbeans.core.startup.NbEvents]: The extension /home/mid/autopsy-autopsy-4.4.0/build/cluster/modules/ext/commons-lang-2.6.jar may be multiply loaded by modules: [/home/mid/autopsy-autopsy-4.4.0/build/cluster/modules/org-sleuthkit-autopsy-corelibs.jar, /home/mid/autopsy-autopsy-4.4.0/build/cluster/modules/org-sleuthkit-autopsy-keywordsearch.jar]; see: http://www.netbeans.org/download/dev/javadoc/org-openide-modules/org/openide/modules/doc-files/classpath.html#class-path
     [exec] Temp Folder for Libraries: /tmp
     [exec] java.lang.AssertionError: Already had dead JAR: /tmp/org-netbeans-api-progress6330495909584454696.jar
     [exec] 	at org.netbeans.JarClassLoader$JarSource.destroy(JarClassLoader.java:700)
     [exec] 	at org.netbeans.JarClassLoader.destroy(JarClassLoader.java:341)
     [exec] 	at org.netbeans.StandardModule.classLoaderDown(StandardModule.java:581)
     [exec] 	at org.netbeans.ModuleManager.enable(ModuleManager.java:1314)
     [exec] 	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
     [exec] 	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
     [exec] 	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
     [exec] 	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
     [exec] 	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
     [exec] 	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
     [exec] 	at org.netbeans.core.startup.Main.start(Main.java:307)
     [exec] 	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
     [exec] 	at java.lang.Thread.run(Thread.java:748)
     [exec] Result: 2

BUILD SUCCESSFUL
Total time: 2 minutes 20 seconds
```

**Comment by rcordovano** [comment]
vitalybalashov, at Basis Technology we are not currently actively supporting Autopsy on Linux, although community efforts to do so are underway.

I can tell you that this error is emitted by an instance of the NetBeans JarClassLoader class when a problem occurs during the loading phase of application start up (the window you described is displayed during loading). As far as I can tell from looking at the NetBeans source code in combination with my team's experiences, the "already had dead JAR" exception is the result of what I believe may be a bug in the NetBeans clean up code, and cannot necessarily be used as an indicator of the actual problem. Here are some error conditions that my team has noted when loading fails and this exception is thrown for our Windows builds:

- Mixing of debug and release builds of the SleuthKit and Autopsy so that library files are not found 
- Incorrect Installer class path in manifest for an NBM in the Autopsy modules suite
- Attempting to start the application in the IDE with an installed version running (for this one, the copy of the JAR referenced in the exception was already written by the running instance, so this error condition is actually directly related) 

Sincerely,
Autopsy Team Lead
Director of Engineering - Digital Forensics, Basis Technology
617-386-7156

**Comment by jmvbxx** [comment]
This is an unfortunate answer because the non-Windows community is large and generally work quite well together. Under normal circumstances I avoid solutions with such narrow visions but in this case, unfortunately, Autopsy is the superior solution. Hopefully, one day, you'll come to realize it and extend service beyond a single slice of the pie.

**Comment by bcarrier** [comment]
@jmvbxx, no project has infinite resources and scope. The Basis Technology team is 99% focused on Windows because that is what our customers pay us to work on. Everything that we do, we design it so that it should be possible to work on both Windows and non-Windows platforms.  

We always welcome community contributions and pull requests to fix code so that it works on non-Windows platforms and we try to provide guidance, like @rcordovano did in this thread, when people are encountering problems on non-Windows platforms.  But, the community needs someone who has the time and interest to debug this issue further and submit a pull request if people want it fixed.

**Comment by rcordovano** [comment]
Please note that in my previous response to this issue I said the following to make it clear that I do not have personal experience with Linux builds of Autopsy:

"vitalybalashov, at Basis Technology we are not currently actively supporting Autopsy on Linux, although community efforts to do so are underway."

 However,  I then went on to provide some information that is not specific to Windows, so @jmvbxx, I am trying to support the Linux community to the extent that I can, within the limitations noted by @bcarrier:

"I can tell you that this error is emitted by an instance of the NetBeans JarClassLoader class when a problem occurs during the loading phase of application start up (the window you described is displayed during loading). As far as I can tell from looking at the NetBeans source code in combination with my team's experiences, the "already had dead JAR" exception is the result of what I believe may be a bug in the NetBeans clean up code, and cannot necessarily be used as an indicator of the actual problem. Here are some error conditions that my team has noted when loading fails and this exception is thrown for our Windows builds:

Mixing of debug and release builds of the SleuthKit and Autopsy so that library files are not found
Incorrect Installer class path in manifest for an NBM in the Autopsy modules suite
Attempting to start the application in the IDE with an installed version running (for this one, the copy of the JAR referenced in the exception was already written by the running instance, so this error condition is actually directly related)."


Sincerely,
Richard Cordovano
Autopsy Team Lead
Director of Engineering - Digital Forensics, Basis Technology

**Comment by jmvbxx** [comment]
@rcordovano I understand your limitations. Thank you for your reply. For now I will simply have to settle for version 2 as I am working against a tight deadline. After that settles I'll come back and take another look.

**Comment by PeterPilley** [comment]
@rcordovano and @bcarrier what sort of funding would it take to re-look at this working in linux again. I know paladin have version 3.11 running fine so maybe this is just a bug for version 4? 

But I would be interested in knowing what we would need to fund to get this supported especially since we are trying to promote Autopsy with other frameworks like ProjectVIC

**Comment by dereklathan** [comment]
I had the same problem. I'm using openjdk instead of Oracle's jdk. The unhandled exception is thrown from the validate method in Core/src/org/sleuthkit/autopsy/datamodel/Installer.java. I tried simply commenting out all the code in that method just to see what happens and it started.

**Comment by dereklathan** [comment]
OK, so now I can't create a case: 

     [exec] org.sleuthkit.autopsy.casemodule.CaseActionException: /tmp/libtsk_jni.so: /tmp/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1637)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:663)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:461)
     [exec] 	at org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:82)
     [exec] 	at org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:74)
     [exec] 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [exec] 	at java.lang.Thread.run(Thread.java:748)
     [exec] Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /tmp/libtsk_jni.so: /tmp/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
     [exec] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [exec] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1602)
     [exec] 	... 10 more
     [exec] Caused by: java.lang.UnsatisfiedLinkError: /tmp/libtsk_jni.so: /tmp/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
     [exec] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     [exec] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
     [exec] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
     [exec] 	at java.lang.Runtime.load0(Runtime.java:809)
     [exec] 	at java.lang.System.load(System.java:1086)
     [exec] 	at org.sleuthkit.datamodel.LibraryUtils.loadNativeLibFromTskJar(LibraryUtils.java:207)
     [exec] 	at org.sleuthkit.datamodel.LibraryUtils.loadSleuthkitJNI(LibraryUtils.java:73)
     [exec] 	at org.sleuthkit.datamodel.SleuthkitJNI.<clinit>(SleuthkitJNI.java:52)
     [exec] 	at org.sleuthkit.datamodel.SleuthkitCase.newCase(SleuthkitCase.java:1194)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.createCaseData(Case.java:1730)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1661)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.lambda$open$4(Case.java:1573)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	... 3 more
     [exec] 
     [exec] Sep 27, 2017 11:20:14 AM org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1 done
     [exec] SEVERE: Error creating case test
     [exec] java.util.concurrent.ExecutionException: org.sleuthkit.autopsy.casemodule.CaseActionException: /tmp/libtsk_jni.so: /tmp/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
     [exec] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [exec] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [exec] 	at javax.swing.SwingWorker.get(SwingWorker.java:602)
     [exec] 	at org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.done(NewCaseWizardAction.java:89)
     [exec] 	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
     [exec] 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
     [exec] 	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
     [exec] 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
     [exec] 	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
     [exec] 	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
     [exec] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
     [exec] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
     [exec] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
     [exec] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
     [exec] 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
     [exec] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
     [exec] 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
     [exec] 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
     [exec] 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
     [exec] 	at java.awt.Dialog.show(Dialog.java:1084)
     [exec] 	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1086)
     [exec] 	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1136)
     [exec] 	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1108)
     [exec] 	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:131)
     [exec] 	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
     [exec] 	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
     [exec] 	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
     [exec] 	at org.openide.util.Mutex.readAccess(Mutex.java:218)
     [exec] 	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1093)
     [exec] 	at java.awt.Component.show(Component.java:1671)
     [exec] 	at java.awt.Component.setVisible(Component.java:1623)
     [exec] 	at java.awt.Window.setVisible(Window.java:1014)
     [exec] 	at java.awt.Dialog.setVisible(Dialog.java:1005)
     [exec] 	at org.sleuthkit.autopsy.progress.ModalDialogProgressIndicator.displayDialog(ModalDialogProgressIndicator.java:260)
     [exec] 	at org.sleuthkit.autopsy.progress.ModalDialogProgressIndicator.lambda$start$1(ModalDialogProgressIndicator.java:120)
     [exec] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
     [exec] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
     [exec] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
     [exec] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
     [exec] 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
     [exec] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     [exec] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
     [exec] Caused by: org.sleuthkit.autopsy.casemodule.CaseActionException: /tmp/libtsk_jni.so: /tmp/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1637)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:663)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:461)
     [exec] 	at org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:82)
     [exec] 	at org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:74)
     [exec] 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [exec] 	at java.lang.Thread.run(Thread.java:748)
     [exec] Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /tmp/libtsk_jni.so: /tmp/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
     [exec] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [exec] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1602)
     [exec] 	... 10 more
     [exec] Caused by: java.lang.UnsatisfiedLinkError: /tmp/libtsk_jni.so: /tmp/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
     [exec] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     [exec] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
     [exec] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
     [exec] 	at java.lang.Runtime.load0(Runtime.java:809)
     [exec] 	at java.lang.System.load(System.java:1086)
     [exec] 	at org.sleuthkit.datamodel.LibraryUtils.loadNativeLibFromTskJar(LibraryUtils.java:207)
     [exec] 	at org.sleuthkit.datamodel.LibraryUtils.loadSleuthkitJNI(LibraryUtils.java:73)
     [exec] 	at org.sleuthkit.datamodel.SleuthkitJNI.<clinit>(SleuthkitJNI.java:52)
     [exec] 	at org.sleuthkit.datamodel.SleuthkitCase.newCase(SleuthkitCase.java:1194)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.createCaseData(Case.java:1730)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1661)
     [exec] 	at org.sleuthkit.autopsy.casemodule.Case.lambda$open$4(Case.java:1573)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	... 3 more
     [exec]

**Comment by mckeowbc** [comment]
It looks like this may be resolved in Autopsy 4.5.0.  A couple of us got it working on Ubuntu while attending #OSDFCon.

**Comment by jmvbxx** [comment]
That's fantastic news! I'll give it a shot this week!

**Comment by bcarrier** [comment]
FYI: As part of our efforts of Autopsy on Linux, we've been coming across this too. In one situation, the /tmp/libtsk_jni.so file existed and was owned by root, but when Autopsy was run again as non-root it could not delete the existing file and therefore could not load the library. 

As Richard said though, this error message is vague and everyone could be seeing it for different reasons.
