### ISSUE TITLE
3.0.8 and JRE7-45 

### ISSUE THREAD

**Issue by adprotas** [sleuthkit/autopsy#363]
Hi,

3.0.8 does not seem to work with JRE 7 v 45, 32-bit.

I have tried this with the distributed installer, as well as the devplatform (I am trying to develop an ingest module).  OS is Win7-64 SP1.

When started, the splash screen freezes on the "Starting Modules".

The stack trace is below:
RenderJob.run: internal exception
java.lang.UnsatisfiedLinkError: com.sun.prism.d3d.D3DContext.nSetBlendEnabled(JZZ)I
	at com.sun.prism.d3d.D3DContext.nSetBlendEnabled(Native Method)
	at com.sun.prism.d3d.D3DContext.initState(D3DContext.java:84)
	at com.sun.prism.d3d.D3DResourceFactory.<init>(D3DResourceFactory.java:57)
	at com.sun.prism.d3d.D3DPipeline.createResourceFactory(D3DPipeline.java:150)
	at com.sun.prism.d3d.D3DPipeline.getD3DResourceFactory(D3DPipeline.java:156)
	at com.sun.prism.d3d.D3DPipeline.findDefaultResourceFactory(D3DPipeline.java:182)
	at com.sun.prism.d3d.D3DPipeline.getDefaultResourceFactory(D3DPipeline.java:204)
	at com.sun.prism.GraphicsPipeline.getDefaultResourceFactory(GraphicsPipeline.java:97)
	at com.sun.javafx.tk.quantum.QuantumRenderer$3.run(QuantumRenderer.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at com.sun.prism.render.RenderJob.run(RenderJob.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:98)
	at java.lang.Thread.run(Thread.java:744)

I have installed the JRE and JDK for Netbeans, and have verified that other Java apps are working just fine.

Thank you.

**Comment by rcordovano** [comment]
Autopsy 4.1.0 is about to be released and it runs with the JRE for Java 1.8.0 (update 66).
