### ISSUE TITLE
OS X doesn't launch

### ISSUE THREAD

**Issue by PeterisP** [sleuthkit/autopsy#4620]
One more issue with launching the system on OS X, seems different from others.
After following the instructions on https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt (sleuthkit v4.6.5 gets installed by brew), when activating the Autopsy-Core module (Version: 10.14.26) the following error message appears:

Activation failed: StandardModule:org.sleuthkit.autopsy.core jarFile: /Users/pet/Documents/KAV/Tools/autopsy-4.10.0/autopsy/modules/org-sleuthkit-autopsy-core.jar: java.lang.UnsatisfiedLinkError: org.sleuthkit.datamodel.SleuthkitJNI.getVersionNat()Ljava/lang/String;

One aspect that's possibly relevant is that the install instructions specify "Autopsy depends on a specific version of The Sleuth Kit." and require v4.6.0-1 for Linux, however, for OS X it's only "Install The Sleuth Kit from brew" which installs the latest 4.6.5 version.  Is the download (Autopsy 4.10.0) compatible with both 4.6.0 and 4.6.5 Sleuth Kit, or are there specific requirements?

**Comment by xeen3d** [comment]
Hi
i am not a developer from autopsy, i have purchased some time ago working Mac OSx Forensic Software.
But I am working in IT and Security since round about 30 years I run Opensource Sandbox Cuckoo on my Mac without any problems and also sleuth kit (cmd version) also many other open source Software self compiled and also with brew.

I try running autopsy since first Time a osx version is in readme, and not one of hole after that coming versions was running only for one Case.

So if that is not your Hobby buy a working Forensic Solution (round about 3500 $) or make a Bootcamp partition, but last is in my eyes not secure enough you have no Gold Master or can clean the Installation after some or only one Case and if you try investigate malware Infected Images you need such a cleaning mechanism that's why I use OSx for Forensic working here the normal malware does not work same on Linux or other Unix derivates.

But back to the tread, I have never see a real working autopsy on a Mac others running it in a VM with Windows or a VM with Kali linux .

I try that round about 3 Month and believe me I try all Java that can be installed with brew or native not only one of that installations give me a working autopsy.
Start it within a Sandbox or debugger and you get hundreds of missing link Errors like missing beans wrong libs wrong beans version or try using Jumps into own sleuth kit java applet that are wrong or want a version that never works with the installed autopsy.
The nearest installation that I have running start Autopsy but than you cannot work with it :

java.lang.ClassNotFoundException: com.sun.javafx.PlatformUtil
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: com.sun.javafx.PlatformUtil starting from ModuleCL@78182f5b[org.sleuthkit.autopsy.corelibs] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@6acbcfc0]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Caused: java.lang.NoClassDefFoundError: com/sun/javafx/PlatformUtil
	at org.sleuthkit.autopsy.corelibs.SigarLoader.getSigar(SigarLoader.java:46)
	at org.sleuthkit.autopsy.coreutils.PlatformUtil.getPID(PlatformUtil.java:480)
	at org.sleuthkit.autopsy.coreutils.Installer.restored(Installer.java:60)
	at org.sleuthkit.autopsy.core.Installer.restored(Installer.java:322)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:437)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:421)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:441)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.base/java.lang.Thread.run(Thread.java:835)


java.lang.NoClassDefFoundError: com/sun/javafx/PlatformUtil
	at org.sleuthkit.autopsy.corelibs.SigarLoader.getSigar(SigarLoader.java:46)
	at org.sleuthkit.autopsy.coreutils.PlatformUtil.getJavaPIDs(PlatformUtil.java:541)
	at org.sleuthkit.autopsy.keywordsearch.Server.getSolrPIDs(Server.java:404)
	at org.sleuthkit.autopsy.keywordsearch.Server.start(Server.java:480)
	at org.sleuthkit.autopsy.keywordsearch.Installer.restored(Installer.java:49)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:437)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:421)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:441)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.base/java.lang.Thread.run(Thread.java:835)

autopsy on Mac is a never ending story and I know that here are not enough developer with a Mac 
I am not a developer I can not programming Java or mixed java and some other languages, and last but nor least I never would make such a App in Java ;-) 
Java is dangerous and is dead ;-)

And believe me the Errors above are nothing if you try use exact what autopsy need in readme you get much more stronger errors than that above.

I like Projects like autopsy and I wish the developers some day a real working version a windows one will be ok but fur now it is more a Test than ready for daily work, but that is ok we are here in a Open Source Project where many many people investigate hours month or years of their Lifetime and that give their my full respect.


best
Andre
