### ISSUE TITLE
Already had dead JAR

### ISSUE THREAD

**Issue by utahaZZ** [sleuthkit/autopsy#5078]
Hi.

I have run "ant run Autopsy" command after building "Autopsy", but an error has occurred.
> java.lang.AssertionError: Already had dead JAR: C:\Users\ZeroTwo\AppData\Local\Temp\org-netbeans-api-progress7451819770248519774.jar
at org.netbeans.JarClassLoader$JarSource.destroy(JarClassLoader.java:700)
at org.netbeans.JarClassLoader.destroy(JarClassLoader.java:341)
at org.netbeans.StandardModule.classLoaderDown(StandardModule.java:581)
at org.netbeans.ModuleManager.enable(ModuleManager.java:1314)
at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
at org.netbeans.core.startup.Main.start(Main.java:307)
at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
at java.lang.Thread.run(Thread.java:748)
Result: 2
BUILD SUCCESSFUL (total time: 3 minutes 52 seconds)

**Comment by rcordovano** [comment]
There are a number of reasons that message can be emitted, but the most likely reason by a large margin is that you have either not built SleuthKit Java bindings or the correct version of the Sleuthkit Java bindings or the correct target. You need to build the Release_PostgreSQL target of the Java bindings in NetBeans to create the TSK Java bindings JAR. Have you done that?

**Comment by rcordovano** [comment]
Correction: dist_PostgreSQL, not Release_PostgreSQL for the TSK Java bindings JAR build required to build Autopsy.

**Comment by utahaZZ** [comment]
@rcordovano I am currently using Autopsy version 4.12.0 and TSK version 4.6.7.

Netbeans created a jar file using the "ant dist-PostgreSQL" command instead of the Java binding in TSK.

**Comment by utahaZZ** [comment]
@rcordovano 
A build folder was created.

Inside the build folder is the "NATIVELIBS" "Org" folder.

However, there is an empty folder in the "NATIVELIBS" folder, and there is a "datamodel" folder in the "sleuthkit" folder in the org folder.

Is this what I have to do?
