### ISSUE TITLE
Failed to load AndroidModuleFactory

### ISSUE THREAD

**Issue by obilodeau** [sleuthkit/autopsy#5351]
New problem with sleuthkit 4.7.0 and autopsy 4.13.

When creating a new case I get:

```
SEVERE: Failed to load AndroidModuleFactory from /opt/autopsy/autopsy/InternalPythonModules/android/module.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/autopsy/autopsy/InternalPythonModules/android/module.py", line 49, in <module>
    import imo
  File "/opt/autopsy/autopsy/InternalPythonModules/android/imo.py", line 46, in <module>
    from org.sleuthkit.datamodel.blackboardutils import CommunicationArtifactsHelper
ImportError: No module named blackboardutils

	org.python.core.Py.ImportError(Py.java:328)
	org.python.core.imp.import_logic(imp.java:912)
	org.python.core.imp.import_module_level(imp.java:978)
	org.python.core.imp.importName(imp.java:1062)
	org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	org.python.core.PyObject.__call__(PyObject.java:431)
	org.python.core.__builtin__.__import__(__builtin__.java:1232)
	org.python.core.imp.importFromAs(imp.java:1156)
	org.python.core.imp.importFrom(imp.java:1132)
	imo$py.f$0(/opt/autopsy/autopsy/InternalPythonModules/android/imo.py:54)
	imo$py.call_function(/opt/autopsy/autopsy/InternalPythonModules/android/imo.py)
	org.python.core.PyTableCode.call(PyTableCode.java:167)
	org.python.core.PyCode.call(PyCode.java:18)
	org.python.core.imp.createFromCode(imp.java:436)
	org.python.core.imp.createFromSource(imp.java:396)
	org.python.core.imp.loadFromSource(imp.java:661)
	org.python.core.imp.find_module(imp.java:543)
	org.python.core.imp.import_next(imp.java:840)
	org.python.core.imp.import_module_level(imp.java:959)
	org.python.core.imp.importName(imp.java:1062)
	org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	org.python.core.PyObject.__call__(PyObject.java:431)
	org.python.core.__builtin__.__import__(__builtin__.java:1232)
	org.python.core.imp.importOne(imp.java:1081)
	module$py.f$0(/opt/autopsy/autopsy/InternalPythonModules/android/module.py:85)
	module$py.call_function(/opt/autopsy/autopsy/InternalPythonModules/android/module.py)
	org.python.core.PyTableCode.call(PyTableCode.java:167)
	org.python.core.PyCode.call(PyCode.java:18)
	org.python.core.imp.createFromCode(imp.java:436)
	org.python.core.imp.createFromSource(imp.java:396)
	org.python.core.imp.loadFromSource(imp.java:661)
	org.python.core.imp.find_module(imp.java:543)
	org.python.core.imp.import_next(imp.java:840)
	org.python.core.imp.import_module_level(imp.java:959)
	org.python.core.imp.importName(imp.java:1062)
	org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	org.python.core.PyObject.__call__(PyObject.java:431)
	org.python.core.__builtin__.__import__(__builtin__.java:1232)
	org.python.core.imp.importOne(imp.java:1081)
	org.python.pycode._pyx11.f$0(<string>:1)
	org.python.pycode._pyx11.call_function(<string>)
	org.python.core.PyTableCode.call(PyTableCode.java:167)
	org.python.core.PyCode.call(PyCode.java:18)
	org.python.core.Py.runCode(Py.java:1386)
	org.python.core.Py.exec(Py.java:1430)
	org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	org.sleuthkit.autopsy.python.JythonModuleLoader.createObjectFromScript(JythonModuleLoader.java:138)
	org.sleuthkit.autopsy.python.JythonModuleLoader.getInterfaceImplementations(JythonModuleLoader.java:106)
	org.sleuthkit.autopsy.python.JythonModuleLoader.getIngestModuleFactories(JythonModuleLoader.java:60)
	org.sleuthkit.autopsy.ingest.IngestModuleFactoryLoader.getIngestModuleFactories(IngestModuleFactoryLoader.java:129)
	org.sleuthkit.autopsy.ingest.IngestJobSettings.load(IngestJobSettings.java:315)
	org.sleuthkit.autopsy.ingest.IngestJobSettings.<init>(IngestJobSettings.java:118)
	org.sleuthkit.autopsy.ingest.IngestJobSettings.<init>(IngestJobSettings.java:93)
	org.sleuthkit.autopsy.casemodule.AddImageWizardIngestConfigPanel.<init>(AddImageWizardIngestConfigPanel.java:58)
	org.sleuthkit.autopsy.casemodule.AddImageWizardIterator.getPanels(AddImageWizardIterator.java:62)
	org.sleuthkit.autopsy.casemodule.AddImageWizardIterator.current(AddImageWizardIterator.java:132)
	org.sleuthkit.autopsy.casemodule.AddImageWizardIterator.current(AddImageWizardIterator.java:37)
[...]
```

I tried to make changes to sleuthkit's `Makefile.am` to include `blackboardutils` directory in the `make dist-gzip` target. I see the files in the sleuthkit jar I build now but I still get that error. Its like there's an import folder definition missing or something.

**Comment by obilodeau** [comment]
![autopsy-4 13-communicationArtifactsHelper](https://user-images.githubusercontent.com/546325/67066720-c1e9bd00-f141-11e9-8367-874640624e7b.png)

**Comment by esaunders** [comment]
I'm trying to reproduce this issue (without success so far). Can you describe the steps you took to get into this state? Thanks.

**Comment by esaunders** [comment]
Ok, I understand what you were trying to do now and can reproduce.

**Comment by esaunders** [comment]
Your change to Makefile.am solves the issue for me. Thanks.

If you are still having issues, confirm that the contents of the sleuthkit-4.7.0.tar.gz contain the blackboardutils java files.

**Comment by obilodeau** [comment]
Yes, it looks like the changes did fix this. I'm unable to reproduce now.
