### ISSUE TITLE
Failed to load AndroidModuleFactory

### ISSUE THREAD

**Issue by blkblt412** [sleuthkit/autopsy#5391]
`SEVERE: Failed to load AndroidModuleFactory from /usr/share/autopsy/autopsy/InternalPythonModules/android/module.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/autopsy/autopsy/InternalPythonModules/android/module.py", line 49, in <module>
    import imo
  File "/usr/share/autopsy/autopsy/InternalPythonModules/android/imo.py", line 46, in <module>
    from org.sleuthkit.datamodel.blackboardutils import CommunicationArtifactsHelper
ImportError: No module named blackboardutils
`
Currently running Arch Linux with Oracle JDK 8 (tried OpenJDK 8 as well) and Autopsy 4.13.0

**Comment by blkblt412** [comment]
Didn't realize this was a duplicate issue, closing and will look at resolution for previous posted issue
