### ISSUE TITLE
RecentActivity failing on ExtractRegistry

### ISSUE THREAD

**Issue by xQsme** [sleuthkit/autopsy#5611]
Output:
```
SEVERE: Exception occurred in Registry
java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at org.sleuthkit.autopsy.recentactivity.ExtractRegistry.parseAutopsyPluginOutput(ExtractRegistry.java:439)
```
Module Outputs:
```
[xqsme@xqsme reg]$ cat NTUSER.DAT-regripper-644-autopsy.err.txt 
Can't locate Parse/Win32Registry.pm in @INC (you may need to install the Parse::Win32Registry module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/xqsme/projects/autopsy/build/cluster/rr/rip.pl line 28.
BEGIN failed--compilation aborted at /home/xqsme/projects/autopsy/build/cluster/rr/rip.pl line 28.
```
```
Can't locate Parse/Win32Registry.pm in @INC (you may need to install the Parse::Win32Registry module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/xqsme/projects/autopsy/build/cluster/rr-full/rip.pl line 28.
BEGIN failed--compilation aborted at /hohttps://github.com/gitpan/Parse-Win32Registryme/xqsme/projects/autopsy/build/cluster/rr-full/rip.pl line 28.
```
By installing https://github.com/gitpan/Parse-Win32Registry I was able to get it to work properly, is this supposed to be a dependency? (the module seems to be contained inside both rr and rr-full).
Edit: Forgot to mention, this is while running in Linux.

**Comment by xQsme** [comment]
Seems like the dependency I installed doesn't fully solve the issue as more includes fail after this one, even though rr-full contains all the files needed

**Comment by markmckinnon** [comment]
It appears that you are running Autopsy in Linux, is this the case?  If so what flavor and version are you running it in.

**Comment by xQsme** [comment]
@markmckinnon Linux Mint, TSK 4.8.0, Autopsy 4.13, migrated from CentOS recently and didn't have this issue back then

**Comment by xQsme** [comment]
solved it by adding the parameter -I (capital i) and the home of the module to the cmds
```
rrCmd.add(perl);
rrCmd.add("-I");
rrCmd.add(rrHome.toString());
rrCmd.add(rrPath);
rrFullCmd.add(perl);
rrFullCmd.add("-I");
rrFullCmd.add(rrFullHome.toString());
rrFullCmd.add(rrFullPath);
```

**Comment by markmckinnon** [comment]
A pull request #5636 has been submitted to address this issue in newer releases.
