### ISSUE TITLE
Autopsy 4.19.3 hangs on add data source

### ISSUE THREAD

**Issue by murdock9999** [sleuthkit/autopsy#7593]
When I create a case and try to add a data source nothing happens, only the cursor changes to the waiting circle type. There appears an exception that is:

```
java.lang.NoClassDefFoundError: Could not initialize class org.python.core.Py
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:99)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)
	at org.sleuthkit.autopsy.python.JythonModuleLoader.getInterfaceImplementations(JythonModuleLoader.java:82)
	at org.sleuthkit.autopsy.python.JythonModuleLoader.getIngestModuleFactories(JythonModuleLoader.java:62)
	at org.sleuthkit.autopsy.ingest.IngestModuleFactoryLoader.getIngestModuleFactories(IngestModuleFactoryLoader.java:130)
	at org.sleuthkit.autopsy.ingest.IngestJobSettings.load(IngestJobSettings.java:316)
	at org.sleuthkit.autopsy.ingest.IngestJobSettings.<init>(IngestJobSettings.java:119)
	at org.sleuthkit.autopsy.ingest.IngestJobSettings.<init>(IngestJobSettings.java:94)
	at org.sleuthkit.autopsy.casemodule.AddImageWizardIngestConfigPanel.<init>(AddImageWizardIngestConfigPanel.java:58)
	at org.sleuthkit.autopsy.casemodule.AddImageWizardIterator.getPanels(AddImageWizardIterator.java:68)
	at org.sleuthkit.autopsy.casemodule.AddImageWizardIterator.current(AddImageWizardIterator.java:139)
	at org.sleuthkit.autopsy.casemodule.AddImageWizardIterator.current(AddImageWizardIterator.java:38)
	at org.openide.WizardDescriptor.updateStateOpen(WizardDescriptor.java:820)
	at org.openide.WizardDescriptor.updateState(WizardDescriptor.java:797)
	at org.openide.WizardDescriptor._updateState(WizardDescriptor.java:775)
	at org.openide.WizardDescriptor.initialize(WizardDescriptor.java:450)
	at org.openide.NotifyDescriptor.getterCalled(NotifyDescriptor.java:279)
	at org.openide.DialogDescriptor.isModal(DialogDescriptor.java:297)
	at org.netbeans.core.windows.services.NbDialog.<init>(NbDialog.java:42)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$1.run(DialogDisplayerImpl.java:133)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$1.run(DialogDisplayerImpl.java:94)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:115)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:75)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:193)
	at org.netbeans.core.windows.services.DialogDisplayerImpl.createDialog(DialogDisplayerImpl.java:94)
	at org.netbeans.core.windows.services.DialogDisplayerImpl.createDialog(DialogDisplayerImpl.java:86)
	at org.sleuthkit.autopsy.casemodule.AddImageAction.actionPerformed(AddImageAction.java:135)
	at org.sleuthkit.autopsy.casemodule.AddImageAction$1.actionPerformed(AddImageAction.java:106)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

OS: Windows 10 x64 Turkish

There are no Turkish characters on my user name or the path of the autopsy installation and the case path.

![autopsy](https://user-images.githubusercontent.com/35687158/162269529-54cd1ffc-6e39-42be-8ec2-4efdb91c6774.png)

[autopsy.log.0.txt](https://github.com/sleuthkit/autopsy/files/8445484/autopsy.log.0.txt)
[autopsy.log.1.txt](https://github.com/sleuthkit/autopsy/files/8445485/autopsy.log.1.txt)
[ThreadDump_2022_04_07_21_10_43.txt](https://github.com/sleuthkit/autopsy/files/8445458/ThreadDump_2022_04_07_21_10_43.txt)
.

**Comment by murdock9999** [comment]
I changed the system language to English (US) and the problem is gone. I can add data source now.

For the Turkish users:

Autopsy programında "Add data source" tıklandığında sistem takılıyor ve herhangi bir pencere açılmıyorsa, Windows dilini İngilizce olarak değiştirince düzgün çalışmaya başlıyor.
