### ISSUE TITLE
M1 Mac Monterey sleuthkit-4.12.0.jar not found in /usr/share/java/ or /usr/local/share/java/

### ISSUE THREAD

**Issue by Ba12ley** [sleuthkit/autopsy#7793]
Hello

I am stuck trying to get this final step to work.  I have followed the Readme and ran the scripts, but unable to solve this issuse.

Running the install_application.sh results in

```
--------------------------------------------
Checking prerequisites and preparing autopsy:
---------------------------------------------
~/autopsy/autopsy-4.20.0 ~/autopsy/autopsy-4.20.0
Checking for PhotoRec...found in /usr/local/bin
Checking for Java...Checking for Sleuth Kit Java bindings...ERROR: sleuthkit-4.12.0.jar not found in /usr/share/java/ or /usr/local/share/java/.
Please install the Sleuth Kit Java bindings file.
See https://github.com/sleuthkit/sleuthkit/releases.
```

Having found the sleuthkit-4.12.0.jar and copied into /usr/local/share/java 

```
---------------------------------------------
Checking prerequisites and preparing autopsy:
---------------------------------------------
~/autopsy/autopsy-4.20.0 ~/autopsy/autopsy-4.20.0
Checking for PhotoRec...found in /usr/local/bin
Checking for Java...Checking for Sleuth Kit Java bindings...found in /usr/local/share/java
Copying sleuthkit-4.12.0.jar into the autopsy directory...done
~/autopsy/autopsy-4.20.0

Application is now configured. You can execute bin/autopsy to start it

```
But when starting the application a blank window opens.

```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Jun 07, 2023 9:44:50 PM org.netbeans.ProxyURLStreamHandlerFactory register
SEVERE: No way to find original stream handler for jar protocol
java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.net.URLStreamHandler java.net.URL.handler accessible: module java.base does not "opens java.net" to unnamed module @2719fe5c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.netbeans.ProxyURLStreamHandlerFactory.register(ProxyURLStreamHandlerFactory.java:59)
	at org.netbeans.JarClassLoader.<clinit>(JarClassLoader.java:117)
	at org.netbeans.MainImpl.execute(MainImpl.java:153)
	at org.netbeans.MainImpl.main(MainImpl.java:60)
	at org.netbeans.Main.main(Main.java:58)

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/Users/home/autopsy/autopsy-4.20.0/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
```

Any help would be welcome

**Comment by markmckinnon** [comment]
What version of Java are you running?

**Comment by Ba12ley** [comment]
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)

**Comment by markmckinnon** [comment]
For 4.20 that will be an issue since it only supports Java 1.8. Next release of Autopsy will support 1.17.

**Comment by Ba12ley** [comment]
Thank you for the help, that has fixed my issue.
